# Generated by Django 3.0.5 on 2020-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_image', models.ImageField(upload_to='')),
                ('partner_first_name', models.CharField(max_length=20)),
                ('partner_second_name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('full_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('emergency_number', models.CharField(max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('licsence_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('availability_status', models.CharField(choices=[('idle', 'idle'), ('on_task', 'on_task')], max_length=7)),
            ],
        ),
    ]
