# Generated by Django 3.0.5 on 2020-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_partners', '0002_auto_20200424_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(upload_to='../static'),
        ),
    ]
