# Generated by Django 3.0.5 on 2020-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_partners', '0005_auto_20200424_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_image',
            field=models.ImageField(max_length=255, upload_to='partner_img/%Y/%m/'),
        ),
    ]
